#!/usr/bin/env python3
"""Generate notebooks/extension_pilots.ipynb: plots + simple explanations of
the four locally-run extension pilots (audit recap, REACH, MBR, conformal,
FUSE). Everything loads the committed artifacts under reports/extensions/,
so the notebook runs anywhere the repo is checked out, no GPU, no torch.

Run: python3 scripts/extensions/build_pilots_notebook.py
"""

from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []
md = lambda s: cells.append(nbf.v4.new_markdown_cell(s))
code = lambda s: cells.append(nbf.v4.new_code_cell(s))

# --------------------------------------------------------------------------- #
md(
    "# Extension pilots, explained\n"
    "\n"
    "Plots and plain-language explanations of the four extension pilots we ran "
    "locally on the trained models' outputs. Everything here loads committed "
    "files (no GPU, no torch needed), so anyone on the team can re-run it.\n"
    "\n"
    "**The story so far, in three sentences.** We reproduced the COSETTE/MARIUS "
    "paper (arXiv:2508.14910) and found its 'generative model is competitive with "
    "the traditional baseline on small data' claim does not hold in our Beauty "
    "setup (faithful SASRec++ R@10 9.06 vs MARIUS 8.17). We then measured what "
    "the paper barely measured: diversity, catalog coverage, and popularity "
    "bias, and found a sharper failure mode on Sports: MARIUS reaches only "
    "about 39% of the catalog at top 10, while SASRec++ reaches about 74%. The "
    "pilots below diagnose why this happens and which intervention paths remain "
    "credible.\n"
    "\n"
    "| Pilot | Question | Status |\n"
    "|---|---|---|\n"
    "| Audit | How do the two models differ beyond accuracy? | done |\n"
    "| REACH | WHY does MARIUS collapse on Sports? | done (mechanism found) |\n"
    "| MBR | Can re-ranking the beam by consensus help? | done: depth-100 scored tau sweep |\n"
    "| Conformal | Can we give coverage guarantees + uncertainty? | done: depth 20 and 100 |\n"
    "| FUSE | Is the sum-fusion an architectural mistake? | done: null accuracy result |"
)

code(
    "import json, sys\n"
    "from pathlib import Path\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "REPO = Path.cwd()\n"
    "while not (REPO / 'scripts' / 'extensions' / 'beyond_accuracy.py').exists() and REPO != REPO.parent:\n"
    "    REPO = REPO.parent\n"
    "sys.path.insert(0, str(REPO))\n"
    "from scripts.extensions import beyond_accuracy as ba\n"
    "from scripts.extensions.compute_beyond_accuracy import load_support, load_model_recs\n"
    "\n"
    "EXT = REPO / 'reports' / 'extensions'\n"
    "CATS = ['Beauty', 'Sports_and_Outdoors']\n"
    "SHORT = {'Beauty': 'Beauty', 'Sports_and_Outdoors': 'Sports'}\n"
    "SEEDS = [42, 43, 44]\n"
    "COL = {'marius': '#d62728', 'sasrec': '#1f77b4'}\n"
    "plt.rcParams['figure.dpi'] = 110\n"
    "print('repo:', REPO)"
)

# --------------------------------------------------------------------------- #
md(
    "## 1. The audit: same models, opposite behavior on two datasets\n"
    "\n"
    "Both models produce a ranked top-10 for every test user. We measure, over "
    "all users: **coverage** (what fraction of the catalog ever gets "
    "recommended to anyone), **Gini** (how unequally recommendations "
    "concentrate on a few items; higher = more concentrated), and the "
    "**popularity-decile exposure profile** (how the recommendation 'budget' "
    "is spread from the rarest 10% of items, D1, to the most popular 10%, "
    "D10).\n"
    "\n"
    "Read the plots below left to right: on Beauty, MARIUS (red) pushes the "
    "most-popular decile LESS than SASRec++ (blue) and spreads more to "
    "mid-popularity items: the generative model looks healthier. On Sports the "
    "same architecture flips: coverage crashes to 39% and concentration is "
    "HIGHER than the baseline. One architecture, two opposite diversity "
    "profiles: this is not captured by Recall/NDCG alone, and should now be "
    "checked on the larger-dataset reproductions."
)

code(
    "# Coverage and Gini at k=10 from the committed audit CSVs.\n"
    "audit = pd.concat([pd.read_csv(EXT / f'beyond_accuracy_{c}.csv') for c in CATS])\n"
    "a10 = audit[audit.k == 10].set_index(['category', 'model'])\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(12, 3.4))\n"
    "for ax, metric, title, better in zip(\n"
    "        axes, ['coverage_mean', 'gini_mean', 'recall_mean'],\n"
    "        ['Catalog coverage @10 (higher = healthier)',\n"
    "         'Gini concentration @10 (lower = healthier)',\n"
    "         'Recall@10 (accuracy, for context)'], [1, -1, 1]):\n"
    "    x = np.arange(len(CATS))\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        vals = [a10.loc[(c, m), metric] for c in CATS]\n"
    "        ax.bar(x + (i - 0.5) * 0.36, vals, 0.34, label=m.upper(), color=COL[m])\n"
    "        for xi, v in zip(x, vals):\n"
    "            ax.text(xi + (i - 0.5) * 0.36, v, f'{v:.2f}', ha='center', va='bottom', fontsize=8)\n"
    "    ax.set_xticks(x); ax.set_xticklabels([SHORT[c] for c in CATS])\n"
    "    ax.set_title(title, fontsize=9.5); ax.legend(fontsize=8)\n"
    "plt.tight_layout(); plt.show()"
)

code(
    "# Popularity-decile exposure profiles, computed live from the committed Top-K dumps.\n"
    "# D1 = rarest 10% of items, D10 = most popular 10%. Bars = share of all top-10 slots.\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.6), sharey=True)\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    meta, pop, _, t2i = load_support(EXT / 'topk' / cat)\n"
    "    x = np.arange(10)\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        profs = []\n"
    "        for s in SEEDS:\n"
    "            recs, _ = load_model_recs(EXT / 'topk' / cat, m, s, meta, t2i)\n"
    "            profs.append(ba.popularity_decile_exposure(recs, pop, k=10))\n"
    "        prof = np.mean(profs, axis=0)\n"
    "        ax.bar(x + (i - 0.5) * 0.36, prof, 0.34, label=m.upper(), color=COL[m])\n"
    "    ax.set_xticks(x); ax.set_xticklabels([f'D{i+1}' for i in range(10)], fontsize=8)\n"
    "    ax.set_title(f'{SHORT[cat]}: who gets the exposure?', fontsize=10)\n"
    "    ax.set_xlabel('item popularity decile (D10 = blockbusters)', fontsize=8.5)\n"
    "    ax.legend(fontsize=8)\n"
    "axes[0].set_ylabel('share of all top-10 slots')\n"
    "plt.tight_layout(); plt.show()\n"
    "print('Beauty: MARIUS gives the top decile LESS (0.54 vs 0.65) -> more diverse.')\n"
    "print('Sports: MARIUS gives the top decile MORE (0.77 vs 0.75) -> the inversion.')"
)

# --------------------------------------------------------------------------- #
md(
    "## 2. REACH: why MARIUS collapses on Sports\n"
    "\n"
    "**The key idea to hold onto:** a generative recommender can only recommend "
    "an item if it actually *writes that item's 4-digit code* during beam "
    "search. If the beam never writes a code, that item is invisible, no matter "
    "how relevant it would have been. SASRec++ cannot have this problem (it "
    "scores every item directly).\n"
    "\n"
    "So we asked: which items can MARIUS *never* reach, and why? Three findings:\n"
    "\n"
    "1. **The collapse is real and big.** On Sports, 9,260 items (50% of the "
    "catalog) are never recommended to anyone, by any seed. These items carry "
    "**22% of all the demand in the training data** (vs 5.7% for SASRec++): a "
    "fifth of what users provably want is invisible.\n"
    "2. **The beam does not prune whole top-level categories.** All 256 "
    "first-digit codes get used. The collapse happens at **digit 2**: code "
    "*pairs* (digit1, digit2) that the beam never writes cover 26% of the "
    "Sports catalog, and that alone accounts for half the unreachable items.\n"
    "3. **Sibling competition.** The best predictor of being unreachable is not "
    "an item's own popularity but its **popularity share within its "
    "first-digit code family** (r = -0.62 vs -0.58 for own popularity). "
    "Items sharing a prefix compete; the beam follows the strong siblings and "
    "the weak ones never get written, even mid-popularity ones."
)

code(
    "reach = {c: json.loads((EXT / 'reach' / f'reach_results_{c}.json').read_text()) for c in CATS}\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.6), sharey=True)\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    rows = reach[cat]['structure']['decile_rows']\n"
    "    x = np.arange(10)\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        vals = [100 * r[f'{m}_unreached_frac'] for r in rows]\n"
    "        ax.bar(x + (i - 0.5) * 0.36, vals, 0.34, label=m.upper(), color=COL[m])\n"
    "    ax.set_xticks(x); ax.set_xticklabels([f'D{r[\"decile\"]}' for r in rows], fontsize=8)\n"
    "    ax.set_title(f'{SHORT[cat]}: % of items NEVER recommended, by popularity decile', fontsize=9.5)\n"
    "    ax.set_xlabel('item popularity decile (D1 = rarest)', fontsize=8.5)\n"
    "    ax.legend(fontsize=8)\n"
    "axes[0].set_ylabel('% consistently unreachable')\n"
    "plt.tight_layout(); plt.show()\n"
    "for cat in CATS:\n"
    "    s = reach[cat]['structure']\n"
    "    print(f\"{SHORT[cat]}: demand mass invisible to MARIUS = {100*s['demand_mass_share_unreached']:.1f}% \"\n"
    "          f\"(SASRec++ {100*s['sasrec_demand_mass_share_unreached']:.1f}%); \"\n"
    "          f\"items only MARIUS misses = {s['overlap']['only_marius']}\")"
)

code(
    "# The mechanism: where in the 4-digit code does the collapse happen?\n"
    "# Within each item-popularity quintile (Q1 rare .. Q5 popular), compare items whose\n"
    "# CODE-PAIR family (digits 1+2) is weak vs strong in training data.\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.6), sharey=True)\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    t = reach[cat]['mechanism']['table_l12']\n"
    "    x = np.arange(5)\n"
    "    lo = [100 * r['unreached_low'] for r in t]\n"
    "    hi = [100 * r['unreached_high'] for r in t]\n"
    "    ax.bar(x - 0.18, lo, 0.34, label='weak pair family (low mass)', color='#ff7f0e')\n"
    "    ax.bar(x + 0.18, hi, 0.34, label='strong pair family (high mass)', color='#2ca02c')\n"
    "    ax.set_xticks(x); ax.set_xticklabels([f'Q{r[\"quintile\"]}' for r in t], fontsize=9)\n"
    "    ax.set_title(f'{SHORT[cat]}: unreachable % by code-pair strength', fontsize=9.5)\n"
    "    ax.set_xlabel('item popularity quintile (Q1 = rare items)', fontsize=8.5)\n"
    "    ax.legend(fontsize=8)\n"
    "axes[0].set_ylabel('% unreachable (MARIUS, top-10)')\n"
    "plt.tight_layout(); plt.show()\n"
    "for cat in CATS:\n"
    "    mech = reach[cat]['mechanism']\n"
    "    q3 = mech['table_l12'][2]\n"
    "    print(f\"{SHORT[cat]}: mid-popularity (Q3) items: {100*q3['unreached_low']:.0f}% unreachable in weak \"\n"
    "          f\"pair families vs {100*q3['unreached_high']:.0f}% in strong ones; \"\n"
    "          f\"never-written pairs cover {100*mech['pair_never_emitted_frac']:.1f}% of the catalog \"\n"
    "          f\"= {100*mech['unreached_share_pair_never']:.0f}% of all unreachable items.\")\n"
    "print()\n"
    "print('Same-quintile items, very different fates: the code FAMILY, not the item itself,')\n"
    "print('decides reachability. The beam prunes weak (digit1, digit2) branches at step 2.')"
)

# --------------------------------------------------------------------------- #
md(
    "## 3. MBR: re-ranking the beam by consensus\n"
    "\n"
    "MARIUS ranks its 20 beam candidates purely by likelihood ('most probable "
    "first'), which is popularity-biased. **Minimum Bayes Risk (MBR)** is an "
    "old idea from machine translation: instead of the single most probable "
    "guess, prefer the guess that most *agrees* with the model's other "
    "guesses. Here, two candidates 'agree' if their codes share a long prefix "
    "(they sit in the same branch of the code tree).\n"
    "\n"
    "The scored depth-100 version is now complete. MBR is **not** an accuracy "
    "fix: the original beam order remains best on Recall@10. It is still a "
    "useful serving-time dial. On Sports, tau=0.5 moves coverage from 0.39 to "
    "0.52 and tail recall from 0.011 to 0.015, while Recall@10 drops from "
    "0.047 to 0.041. Uniform MBR is the most diversity-heavy lower bound and "
    "loses much more accuracy."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.8))\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    pts = {}\n"
    "    for var in ['tau0.5', 'tau1.0', 'tau2.0', 'uniform']:\n"
    "        df = pd.read_csv(EXT / 'mbr' / f'mbr_{cat}_d100_{var}.csv')\n"
    "        m = df.groupby('variant')[['recall', 'coverage', 'arp', 'tail_recall']].mean()\n"
    "        pts['beam'] = m.loc['original']; pts[var] = m.loc['mbr']\n"
    "    order = ['beam', 'tau0.5', 'tau1.0', 'tau2.0', 'uniform']\n"
    "    xs = [pts[p]['recall'] * 100 for p in order]\n"
    "    ys = [pts[p]['coverage'] for p in order]\n"
    "    ax.plot(xs, ys, '-', color='#c7c7c7', lw=1)\n"
    "    ax.scatter(xs[1:], ys[1:], color='#2ca02c', s=45, label='MBR')\n"
    "    ax.scatter(xs[0], ys[0], color=COL['marius'], s=70, label='beam')\n"
    "    for p, x0, y0 in zip(order, xs, ys):\n"
    "        ax.annotate(p, (x0, y0), textcoords='offset points', xytext=(5, 4), fontsize=8)\n"
    "    ax.set_xlabel('Recall@10 (%)')\n"
    "    ax.set_ylabel('catalog coverage')\n"
    "    ax.set_title(f'{SHORT[cat]}: accuracy vs reach')\n"
    "    ax.legend(fontsize=8)\n"
    "plt.tight_layout(); plt.show()\n"
    "\n"
    "sports = pd.read_csv(EXT / 'mbr' / 'mbr_Sports_and_Outdoors_d100_tau0.5.csv')\n"
    "m = sports.groupby('variant')[['recall', 'coverage', 'arp', 'tail_recall']].mean()\n"
    "print('Sports tau=0.5:')\n"
    "for metric in ['recall', 'coverage', 'arp', 'tail_recall']:\n"
    "    print(f'  {metric}: {m.loc[\"original\", metric]:.4f} -> {m.loc[\"mbr\", metric]:.4f}')"
)

# --------------------------------------------------------------------------- #
md(
    "## 4. Conformal sets: turning a weaker model into a reliable one\n"
    "\n"
    "Instead of 'here are 10 guesses', conformal prediction returns a set with "
    "a **statistical guarantee**: 'the true next item is in this set at least "
    "c% of the time'. The guarantee is distribution-free; you calibrate a "
    "set-size threshold on held-out users and it provably transfers.\n"
    "\n"
    "Two honest findings. First, a **ceiling**: with one held-out item per user, "
    "the best guaranteeable coverage is the model's Recall at the dump depth, "
    "so conventional 90% guarantees are impossible here. Depth 100 roughly "
    "doubles the ceiling and creates a useful crossover: at depth 20 SASRec++ "
    "has the higher ceiling, but at depth 100 MARIUS does on both datasets. "
    "Second, calibrating separately per user group (Mondrian) makes **set size "
    "an uncertainty meter**. On Beauty, cold users need much larger sets than "
    "warm users; on Sports the signal is flatter, consistent with the collapse."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.6))\n"
    "# Left: depth-20 vs depth-100 ceiling crossover.\n"
    "x = np.arange(len(CATS))\n"
    "for j, (dirname, colname, depth) in enumerate([('conformal', 'ceiling_recall20_all', 20),\n"
    "                                                ('conformal_d100', 'ceiling_recall_all', 100)]):\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        vals = [pd.read_csv(EXT / dirname / f'split_conformal_{c}.csv').query('model == @m')[colname].mean()\n"
    "                for c in CATS]\n"
    "        off = (j * 2 + i - 1.5) * 0.2\n"
    "        axes[0].bar(x + off, vals, 0.19, color=COL[m], alpha=0.55 if depth == 20 else 1.0,\n"
    "                    label=f'{m.upper()}, depth {depth}')\n"
    "axes[0].set_xticks(x); axes[0].set_xticklabels([SHORT[c] for c in CATS])\n"
    "axes[0].set_ylabel('coverage ceiling')\n"
    "axes[0].set_title('Recall@depth ceiling')\n"
    "axes[0].legend(fontsize=7.5, ncol=2)\n"
    "# Right: Mondrian set size by user history bucket (Beauty c=0.08, Sports c=0.06).\n"
    "buckets = ['hist<=5', 'hist6-15', 'hist>=16']\n"
    "width = 0.34\n"
    "for ci, (cat, cov) in enumerate([('Beauty', 0.08), ('Sports_and_Outdoors', 0.06)]):\n"
    "    mo = pd.read_csv(EXT / 'conformal' / f'mondrian_{cat}.csv')\n"
    "    mo = mo[(mo.target_coverage == cov) & mo.achievable]\n"
    "    g = mo[mo.model == 'marius'].groupby('bucket')['k_star'].mean().reindex(buckets)\n"
    "    x = np.arange(3)\n"
    "    axes[1].bar(x + (ci - 0.5) * width, g.values, width * 0.94,\n"
    "                label=f'{SHORT[cat]} (c={int(cov*100)}%)',\n"
    "                color=['#d62728', '#9467bd'][ci])\n"
    "axes[1].set_xticks(np.arange(3))\n"
    "axes[1].set_xticklabels(['cold users\\n(<=5 items)', 'medium\\n(6-15)', 'warm\\n(>=16)'], fontsize=8.5)\n"
    "axes[1].set_ylabel('required set size k* (MARIUS)')\n"
    "axes[1].set_title('Set size as an uncertainty meter (Mondrian)', fontsize=10)\n"
    "axes[1].legend(fontsize=8)\n"
    "plt.tight_layout(); plt.show()\n"
    "print('Beauty: cold users need much larger sets than warm users -> a working per-user uncertainty signal.')\n"
    "print('Depth-100 ceiling crossover: MARIUS has the stronger deep candidate pool, but weaker top-of-list ordering.')"
)

# --------------------------------------------------------------------------- #
md(
    "## 5. FUSE: is the sum() an architectural mistake?\n"
    "\n"
    "To feed a user's history into its temporal transformer, MARIUS squashes "
    "each item's 4 code embeddings into ONE vector by simply **adding them up** "
    "(one line: `temp_emb(input).sum(dim=-2)`). That habit was inherited from "
    "audio models. The problem: addition is blind to which digit mattered. Two "
    "items that share their 3 coarse digits and differ only in the fine 4th "
    "digit get almost identical fused vectors, so the model can barely tell "
    "them apart in a user's history (the demo below makes this concrete).\n"
    "\n"
    "We built a subclass (no edits to the authors' code) with three "
    "alternatives, each starting exactly equal to the baseline at "
    "initialization, so training decides if structure helps:\n"
    "\n"
    "- `level_gain`: a learned per-digit volume knob (cheapest fix, +1k params),\n"
    "- `attn`: a tiny attention that re-weights the 4 digits per item (+257 params),\n"
    "- `level_bias`: kept as a control because our selftest PROVED it is a "
    "no-op in disguise (per-digit additive offsets just sum into one constant; "
    "a nice catch that saved a wasted training run).\n"
    "\n"
    "The full 3-seed Beauty runs are complete. Accuracy is unchanged: "
    "`level_gain` reaches R@10 8.29 +/- 0.09 and `attn` reaches 8.23 +/- 0.15, "
    "versus the sum baseline 8.26 +/- 0.20. That makes FUSE a clean negative "
    "for the hypothesis that sum-fusion is the main bottleneck."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(12, 3.6))\n"
    "arms = [('baseline\\n(sum)', EXT / 'baseline_scur1217' / 'marius_beauty_5seed_full_scores.jsonl', '#7f7f7f'),\n"
    "        ('level_gain', EXT / 'fuse' / 'level_gain' / 'marius_beauty_5seed_full_scores.jsonl', '#2ca02c'),\n"
    "        ('attn', EXT / 'fuse' / 'attn' / 'marius_beauty_5seed_full_scores.jsonl', '#9467bd')]\n"
    "def jsonl_metric(path, metric):\n"
    "    rows = [json.loads(l) for l in Path(path).read_text().splitlines() if l.strip()]\n"
    "    vals = [r[metric] for r in rows if r.get('status') == 'ok']\n"
    "    return np.mean(vals), np.std(vals, ddof=1)\n"
    "means = []\n"
    "for xi, (label, path, c) in enumerate(arms):\n"
    "    mean, std = jsonl_metric(path, 'R@10'); means.append(mean)\n"
    "    axes[0].bar(xi, mean, 0.6, yerr=std, color=c, capsize=3)\n"
    "    axes[0].text(xi, mean + 0.06, f'{mean:.2f}', ha='center', fontsize=8)\n"
    "axes[0].set_xticks(range(3)); axes[0].set_xticklabels([a[0] for a in arms])\n"
    "axes[0].set_ylabel('test Recall@10 (%), 3 seeds')\n"
    "axes[0].set_ylim(7.7, 8.7)\n"
    "axes[0].set_title('FUSE accuracy is unchanged')\n"
    "\n"
    "base = pd.read_csv(EXT / 'beyond_accuracy_Beauty.csv')\n"
    "b = base[(base.model == 'marius') & (base.k == 10)].iloc[0]\n"
    "metrics = [('coverage_mean', 'coverage'), ('tail_recall_mean', 'tail recall'),\n"
    "           ('aplt_mean', 'long-tail share'), ('gini_mean', 'Gini'), ('arp_mean', 'avg popularity')]\n"
    "y = np.arange(len(metrics))\n"
    "for i, (arm, c) in enumerate([('level_gain', '#2ca02c'), ('attn', '#9467bd')]):\n"
    "    df = pd.read_csv(EXT / 'fuse' / f'beyond_accuracy_Beauty_{arm}.csv')\n"
    "    row = df[df.k == 10].iloc[0]\n"
    "    rel = [100 * (row[mc] - b[mc]) / b[mc] for mc, _ in metrics]\n"
    "    axes[1].barh(y + (i - 0.5) * 0.36, rel, 0.34, color=c, label=arm)\n"
    "axes[1].axvline(0, color='black', lw=0.8)\n"
    "axes[1].set_yticks(y); axes[1].set_yticklabels([lbl for _, lbl in metrics])\n"
    "axes[1].set_xlabel('% change vs baseline')\n"
    "axes[1].invert_yaxis()\n"
    "axes[1].set_title('Small beyond-accuracy shifts')\n"
    "axes[1].legend(fontsize=8)\n"
    "plt.tight_layout(); plt.show()\n"
    "print('FUSE verdict: null accuracy result; sum-fusion is not the main bottleneck on Beauty.')"
)

# --------------------------------------------------------------------------- #
md(
    "## 6. What happens next\n"
    "\n"
    "The completed pilots narrow the next step. The codebook looks healthy, "
    "the sum-fusion ablation is null, and MARIUS has a stronger depth-100 "
    "candidate pool than its top-10 ranking suggests. The decisive missing "
    "experiment is therefore **exact catalog scoring**:\n"
    "\n"
    "1. Teacher-force every valid item code for a user sample.\n"
    "2. Score each item by exact joint model log-probability.\n"
    "3. Compare exact top-K with beam top-K.\n"
    "4. Decide whether the missing catalog regions are search errors or "
    "model-ranking errors.\n"
    "\n"
    "In parallel, teammates' larger-dataset reproductions should export the "
    "same top-K dumps and support tables so we can measure coverage, "
    "unreachable demand, prefix-family survival, and exact-vs-beam behavior "
    "at scale. Accuracy alone is not enough to answer the reachability question.\n"
    "\n"
    "**How the pieces could become one paper.** The audit found the collapse; "
    "REACH explains it (step-2 pruning of weak code-pair families via sibling "
    "competition); MBR and conformal show decode-time interventions and "
    "calibrated reliability on a frozen model; FUSE tests and weakens the "
    "architectural-fusion hypothesis. After the pilots, the strongest version is: diagnose the "
    "collapse mechanistically, decompose exact model score from beam search, "
    "then implement a mechanism-targeted decoder only if search is responsible.\n"
    "\n"
    "Full details: `reports/extensions/PILOTS.md` (status + numbers), "
    "`.context/extension-decision-brief.md` (the dense decision document), "
    "`.context/extension-explainer.md` (the plain-language explainer)."
)

nb["cells"] = cells
out = Path(__file__).resolve().parents[2] / "notebooks" / "extension_pilots.ipynb"
nbf.write(nb, str(out))
print("wrote", out)
