#!/usr/bin/env python3
"""Generate notebooks/project_story.ipynb: the project end to end, from the
reproduction through the four extension pilots, with all results plotted.

Everything loads committed artifacts under reports/, so the notebook
re-executes anywhere the repo is checked out; no GPU, no torch.

Run: python3 scripts/extensions/build_story_notebook.py
"""

from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
cells = []
md = lambda s: cells.append(nbf.v4.new_markdown_cell(s))
code = lambda s: cells.append(nbf.v4.new_code_cell(s))

# =========================================================================== #
md(
    "# COSETTE & MARIUS: reproduction and extension\n"
    "\n"
    "This notebook presents the project end to end: a reproduction of "
    "*Closing the Performance Gap in Generative Recommenders with "
    "Collaborative Tokenization and Efficient Modeling* (Lepage, Mary, "
    "Picard; arXiv:2508.14910), a beyond-accuracy audit of the trained "
    "models, an analysis of a failure mode the audit surfaced, and four "
    "pilot interventions.\n"
    "\n"
    "All figures are computed from committed artifacts in this repository. "
    "Model accuracy comes from the authors' unmodified evaluation code; the "
    "beyond-accuracy metrics are recomputed from the models' own ranked "
    "outputs and match the official Recall@10 to the decimal.\n"
    "\n"
    "1. The paper and its claims\n"
    "2. Reproduction\n"
    "3. Beyond-accuracy audit\n"
    "4. Reachability: the collapse mechanism\n"
    "5. MBR re-ranking\n"
    "6. Conformal prediction sets\n"
    "7. Fusion ablation\n"
    "8. Synthesis"
)

code(
    "import json, sys\n"
    "from pathlib import Path\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib as mpl\n"
    "import matplotlib.pyplot as plt\n"
    "\n"
    "REPO = Path.cwd()\n"
    "while not (REPO / 'scripts' / 'extensions' / 'beyond_accuracy.py').exists() and REPO != REPO.parent:\n"
    "    REPO = REPO.parent\n"
    "sys.path.insert(0, str(REPO))\n"
    "from scripts.extensions import beyond_accuracy as ba\n"
    "from scripts.extensions.compute_beyond_accuracy import load_support, load_model_recs\n"
    "\n"
    "RES = REPO / 'reports' / 'results'\n"
    "FAITH = REPO / 'reports' / 'paper_faithful_rerun'\n"
    "EXT = REPO / 'reports' / 'extensions'\n"
    "CATS = ['Beauty', 'Sports_and_Outdoors']\n"
    "SHORT = {'Beauty': 'Beauty', 'Sports_and_Outdoors': 'Sports'}\n"
    "\n"
    "# A single muted palette, used consistently throughout.\n"
    "SAS, MAR = '#4c72b0', '#c44e52'          # the two models\n"
    "NEUTRAL, ACCENT, MUTE = '#8c8c8c', '#55a868', '#b0b0b0'\n"
    "COL = {'sasrec': SAS, 'marius': MAR}\n"
    "\n"
    "mpl.rcParams.update({\n"
    "    'figure.dpi': 120, 'savefig.bbox': 'tight', 'figure.facecolor': 'white',\n"
    "    'font.size': 10, 'axes.titlesize': 10.5, 'axes.labelsize': 9.5,\n"
    "    'xtick.labelsize': 8.5, 'ytick.labelsize': 8.5, 'legend.fontsize': 8.5,\n"
    "    'axes.spines.top': False, 'axes.spines.right': False,\n"
    "    'legend.frameon': False, 'axes.titlelocation': 'left', 'axes.titlepad': 8,\n"
    "})\n"
    "\n"
    "def tidy(ax, ygrid=True):\n"
    "    ax.set_axisbelow(True)\n"
    "    ax.tick_params(length=0)\n"
    "    if ygrid:\n"
    "        ax.yaxis.grid(True, color='#e6e6e6', lw=0.8)\n"
    "    return ax\n"
    "\n"
    "def labels(ax, xs, vals, fmt='{:.2f}', dy=0.0):\n"
    "    for x, v in zip(np.atleast_1d(xs), np.atleast_1d(vals)):\n"
    "        ax.annotate(fmt.format(v), (x, v + dy), ha='center', va='bottom',\n"
    "                    fontsize=7.5, color='#555')\n"
    "\n"
    "def jsonl_r10(path):\n"
    "    rows = [json.loads(l) for l in Path(path).read_text().splitlines() if l.strip()]\n"
    "    vals = [r['R@10'] for r in rows if r.get('status') == 'ok']\n"
    "    return float(np.mean(vals)), (float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0)\n"
    "\n"
    "PAPER = {'Beauty': {'sasrec': 9.73, 'marius': 10.02},\n"
    "         'Sports_and_Outdoors': {'sasrec': 6.44, 'marius': 6.72}}"
)

# =========================================================================== #
md(
    "## 1. The paper\n"
    "\n"
    "The paper has two parts. COSETTE assigns each item a four-digit "
    "*semantic ID* with an RQ-VAE over text embeddings, adding a contrastive "
    "term so that co-consumed items receive similar codes. MARIUS is a "
    "lightweight generative recommender: a temporal transformer reads the "
    "user's history (one fused token per past item), and a depth transformer "
    "writes the next item's four code digits autoregressively, with beam "
    "search returning the top candidates.\n"
    "\n"
    "The paper reports that MARIUS is much faster than the prior generative "
    "model (TIGER), beats the tuned discriminative baseline SASRec++ at large "
    "scale, and is competitive with it at small scale (Table 5: Beauty "
    "Recall@10 10.02 vs 9.73). The mandatory reproduction tests the "
    "small-scale claim on Beauty and Sports."
)

# =========================================================================== #
md(
    "## 2. Reproduction\n"
    "\n"
    "Running the repository as released places every metric 15 to 28 percent "
    "below the paper. The main cause is a configuration difference: the paper "
    "selects the baseline size per dataset (appendix Figure 11a; Beauty's "
    "best is d=32 with no normalization), while the repository ships only its "
    "default (d=128 with L2 normalization). Using the paper's configuration "
    "recovers roughly 55 percent of the Beauty gap, from 8.24 to 9.06.\n"
    "\n"
    "MARIUS already uses the paper's configuration, yet the faithful baseline "
    "clearly exceeds it (9.06 vs 8.17 on Beauty). The small-scale "
    "competitiveness claim does not reproduce here. Undertraining, the data "
    "split, the evaluation code, batch size, and tokenizer quality were ruled "
    "out; the validation curve below shows the model converges and mildly "
    "overfits rather than stopping early."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))\n"
    "for ax, cat, slug in zip(axes, CATS, ['beauty', 'sports']):\n"
    "    bars = [\n"
    "        ('default\\nd=128', jsonl_r10(RES / f'sasrec_{slug}_5seed_full_scores.jsonl'), MUTE),\n"
    "        ('faithful\\nd=32', jsonl_r10(FAITH / f'{slug}_d32__scores.jsonl'), SAS),\n"
    "        ('faithful\\nd=64', jsonl_r10(FAITH / f'{slug}_d64__scores.jsonl'), SAS),\n"
    "        ('MARIUS\\n+COSETTE', jsonl_r10(RES / f'marius_{slug}_5seed_full_scores.jsonl'), MAR),\n"
    "    ]\n"
    "    x = np.arange(len(bars))\n"
    "    means = [b[1][0] for b in bars]\n"
    "    ax.bar(x, means, 0.62, yerr=[b[1][1] for b in bars], color=[b[2] for b in bars],\n"
    "           ecolor='#999', capsize=3, error_kw={'lw': 1})\n"
    "    labels(ax, x, means, dy=0.22)\n"
    "    ax.axhline(PAPER[cat]['marius'], color='#bbb', ls=(0, (4, 3)), lw=1)\n"
    "    ax.text(len(bars) - 1, PAPER[cat]['marius'] + 0.1, 'paper MARIUS', ha='right',\n"
    "            fontsize=7.5, color='#999')\n"
    "    ax.set_xticks(x); ax.set_xticklabels([b[0] for b in bars])\n"
    "    ax.set_ylim(0, 11); ax.set_title(SHORT[cat])\n"
    "    tidy(ax)\n"
    "axes[0].set_ylabel('test Recall@10 (%)')\n"
    "fig.suptitle('SASRec++ configurations vs MARIUS+COSETTE (5 seeds)', x=0.5, y=1.0, fontsize=10.5)\n"
    "plt.tight_layout(); plt.show()"
)

code(
    "fig, ax = plt.subplots(figsize=(7, 2.8))\n"
    "frames = []\n"
    "for seed in [42, 43, 44, 45, 46]:\n"
    "    df = pd.read_csv(REPO / 'reports' / 'metrics' / f'sasrec_Beauty_seed{seed}.csv')\n"
    "    df = df[df.metric == 'HR@10']\n"
    "    ax.plot(df.step, 100 * df.value, color='#cfcfcf', lw=0.9)\n"
    "    frames.append(df.set_index('step')['value'])\n"
    "mean = 100 * pd.concat(frames, axis=1).mean(axis=1)\n"
    "ax.plot(mean.index, mean.values, color=SAS, lw=2)\n"
    "ax.set_xlabel('logged step'); ax.set_ylabel('validation HR@10 (%)')\n"
    "ax.set_title('SASRec++ on Beauty: validation peaks early, then declines (converged)')\n"
    "tidy(ax)\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 3. Beyond-accuracy audit\n"
    "\n"
    "Accuracy is only part of the picture. From the models' ranked top-10 "
    "lists we also measure catalog coverage (the fraction of items ever "
    "recommended), the Gini coefficient of exposure (concentration), and the "
    "share of recommendations falling in each item-popularity decile.\n"
    "\n"
    "The two datasets give opposite pictures. On Beauty, MARIUS spreads "
    "exposure more evenly than the baseline and leans less on the most "
    "popular items. On the sparser Sports catalog this reverses: coverage "
    "falls to 0.39 and concentration exceeds the baseline. On both datasets "
    "MARIUS's tail recall is lower, so the Beauty diversity reflects "
    "redistributed exposure rather than more accurate tail predictions."
)

code(
    "audit = pd.concat([pd.read_csv(EXT / f'beyond_accuracy_{c}.csv') for c in CATS])\n"
    "a10 = audit[audit.k == 10].set_index(['category', 'model'])\n"
    "fig, axes = plt.subplots(1, 3, figsize=(11, 3.2))\n"
    "panels = [('coverage_mean', 'catalog coverage', '{:.2f}'),\n"
    "          ('gini_mean', 'Gini (concentration)', '{:.2f}'),\n"
    "          ('tail_recall_mean', 'tail recall', '{:.3f}')]\n"
    "for ax, (metric, title, fmt) in zip(axes, panels):\n"
    "    x = np.arange(len(CATS))\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        vals = [a10.loc[(c, m), metric] for c in CATS]\n"
    "        ax.bar(x + (i - 0.5) * 0.36, vals, 0.34, color=COL[m],\n"
    "               label=m.upper() if ax is axes[0] else None)\n"
    "    ax.set_xticks(x); ax.set_xticklabels([SHORT[c] for c in CATS]); ax.set_title(title)\n"
    "    tidy(ax)\n"
    "axes[0].legend(loc='upper right')\n"
    "fig.suptitle('Beyond-accuracy metrics at k=10', x=0.5, y=1.0, fontsize=10.5)\n"
    "plt.tight_layout(); plt.show()"
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(11, 3.2), sharey=True)\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    meta, pop, _, t2i = load_support(EXT / 'topk' / cat)\n"
    "    x = np.arange(10)\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        profs = [ba.popularity_decile_exposure(load_model_recs(EXT / 'topk' / cat, m, s, meta, t2i)[0], pop, k=10)\n"
    "                 for s in [42, 43, 44]]\n"
    "        ax.bar(x + (i - 0.5) * 0.36, np.mean(profs, axis=0), 0.34, color=COL[m],\n"
    "               label=m.upper() if ax is axes[0] else None)\n"
    "    ax.set_xticks([0, 4, 9]); ax.set_xticklabels(['D1', 'D5', 'D10'])\n"
    "    ax.set_xlabel('item popularity decile'); ax.set_title(SHORT[cat])\n"
    "    tidy(ax)\n"
    "axes[0].set_ylabel('share of top-10 slots'); axes[0].legend(loc='upper left')\n"
    "fig.suptitle('Exposure by popularity decile (D10 = most popular)', x=0.5, y=1.0, fontsize=10.5)\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 4. Reachability: the collapse mechanism\n"
    "\n"
    "A generative recommender can only recommend an item whose code its beam "
    "writes. On Sports, half the catalog (9,260 items) is never written by "
    "any seed; those items carry 22 percent of all training interactions, "
    "against 5.7 percent for the baseline's unreached set.\n"
    "\n"
    "The pruning happens at the second code digit, not the first: all 256 "
    "first digits are used, but digit pairs that are never written cover 26 "
    "percent of the Sports catalog and account for half the unreachable "
    "items. The strongest predictor of unreachability is an item's "
    "popularity share within its first-digit family (point-biserial "
    "r = -0.62), ahead of its own popularity (-0.58): items are pruned in "
    "favour of stronger siblings sharing their prefix. A second, "
    "independently trained Sports tokenizer reproduces these numbers within "
    "one to two points."
)

code(
    "reach = {c: json.loads((EXT / 'reach' / f'reach_results_{c}.json').read_text()) for c in CATS}\n"
    "cb2 = json.loads((EXT / 'reach_cb2' / 'reach_results_Sports_and_Outdoors.json').read_text())\n"
    "fig, axes = plt.subplots(1, 3, figsize=(12, 3.3))\n"
    "\n"
    "rows = reach['Sports_and_Outdoors']['structure']['decile_rows']\n"
    "x = np.arange(10)\n"
    "for i, m in enumerate(['sasrec', 'marius']):\n"
    "    axes[0].bar(x + (i - 0.5) * 0.36, [100 * r[f'{m}_unreached_frac'] for r in rows], 0.34,\n"
    "                color=COL[m], label=m.upper())\n"
    "axes[0].set_xticks([0, 4, 9]); axes[0].set_xticklabels(['D1', 'D5', 'D10'])\n"
    "axes[0].set_xlabel('popularity decile'); axes[0].set_ylabel('% never recommended')\n"
    "axes[0].set_title('items never reached (Sports)'); axes[0].legend(); tidy(axes[0])\n"
    "\n"
    "t = reach['Sports_and_Outdoors']['mechanism']['table_l12']\n"
    "xq = np.arange(5)\n"
    "axes[1].bar(xq - 0.18, [100 * r['unreached_low'] for r in t], 0.34, color=MUTE, label='weak pair family')\n"
    "axes[1].bar(xq + 0.18, [100 * r['unreached_high'] for r in t], 0.34, color=MAR, label='strong pair family')\n"
    "axes[1].set_xticks(xq); axes[1].set_xticklabels([f'Q{r[\"quintile\"]}' for r in t])\n"
    "axes[1].set_xlabel('item popularity quintile'); axes[1].set_ylabel('% unreachable')\n"
    "axes[1].set_title('same popularity, different prefix'); axes[1].legend(); tidy(axes[1])\n"
    "\n"
    "m1, m2 = reach['Sports_and_Outdoors'], cb2\n"
    "names = ['coverage', 'unwritten\\npairs', 'invisible\\ndemand']\n"
    "v1 = [m1['reach']['marius_k10']['mean_reached_frac'], m1['mechanism']['pair_never_emitted_frac'],\n"
    "      m1['structure']['demand_mass_share_unreached']]\n"
    "v2 = [m2['reach']['marius_k10']['mean_reached_frac'], m2['mechanism']['pair_never_emitted_frac'],\n"
    "      m2['structure']['demand_mass_share_unreached']]\n"
    "xv = np.arange(3)\n"
    "axes[2].bar(xv - 0.18, v1, 0.34, color=MAR, label='codebook 1')\n"
    "axes[2].bar(xv + 0.18, v2, 0.34, color='#e0a3a5', label='codebook 2')\n"
    "axes[2].set_xticks(xv); axes[2].set_xticklabels(names)\n"
    "axes[2].set_title('robustness across codebooks'); axes[2].legend(); tidy(axes[2])\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 5. MBR re-ranking\n"
    "\n"
    "The first intervention leaves the model frozen and changes only how the "
    "beam's candidates are ranked. Minimum-Bayes-risk re-ranking prefers "
    "candidates that agree with the model's other guesses (measured by shared "
    "code-prefix length), weighted by the model's own confidence at "
    "temperature tau.\n"
    "\n"
    "MBR does not improve accuracy: the original beam order remains best on "
    "Recall@10. It does provide a serving-time trade-off between accuracy and "
    "reach. On Sports, giving up 0.6 points of Recall@10 raises coverage from "
    "0.39 to 0.52, lowers average recommendation popularity from 101 to 73, "
    "and improves tail recall by about a third (at every tau tested)."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))\n"
    "for ax, cat in zip(axes, CATS):\n"
    "    pts = {}\n"
    "    for var in ['uniform', 'tau0.5', 'tau1.0', 'tau2.0']:\n"
    "        df = pd.read_csv(EXT / 'mbr' / f'mbr_{cat}_d100_{var}.csv')\n"
    "        m = df.groupby('variant')[['recall', 'coverage']].mean()\n"
    "        pts['beam'] = m.loc['original']; pts[var] = m.loc['mbr']\n"
    "    order = ['beam', 'tau0.5', 'tau1.0', 'tau2.0', 'uniform']\n"
    "    xs = [pts[p]['recall'] * 100 for p in order]; ys = [pts[p]['coverage'] for p in order]\n"
    "    ax.plot(xs, ys, '-', color='#d0d0d0', lw=1, zorder=1)\n"
    "    ax.scatter(xs[1:], ys[1:], s=45, color=ACCENT, zorder=3, label='MBR')\n"
    "    ax.scatter(xs[0], ys[0], s=70, color=MAR, zorder=4, label='beam (likelihood)')\n"
    "    for p, xp, yp in zip(order, xs, ys):\n"
    "        ax.annotate(p, (xp, yp), textcoords='offset points', xytext=(5, 4), fontsize=7.5, color='#555')\n"
    "    ax.set_xlabel('Recall@10 (%)'); ax.set_ylabel('catalog coverage'); ax.set_title(SHORT[cat])\n"
    "    ax.legend(loc='lower left'); tidy(ax)\n"
    "fig.suptitle('Accuracy vs reach as tau varies (depth-100 candidates)', x=0.5, y=1.0, fontsize=10.5)\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 6. Conformal prediction sets\n"
    "\n"
    "The second intervention returns a set calibrated to contain the true "
    "next item with a chosen frequency (split conformal on the target's "
    "rank). With one held-out item per user, the guaranteeable coverage is "
    "bounded by Recall@depth, so the practical use is small sets with modest "
    "guarantees plus a per-user uncertainty signal: calibrating separately by "
    "history length, cold users receive visibly larger sets (about 3.4x on "
    "Beauty).\n"
    "\n"
    "The coverage ceilings reveal a crossover. At depth 20 the baseline's "
    "ceiling is higher, but at depth 100 MARIUS's is higher on both datasets. "
    "MARIUS's deeper candidate pool is the stronger one; the ranking of the "
    "top of its list is what limits it, which is consistent with the MBR "
    "result above."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(11, 3.4))\n"
    "x = np.arange(2)\n"
    "specs = [(20, 'conformal', 'ceiling_recall20_all', 0.55),\n"
    "         (100, 'conformal_d100', 'ceiling_recall_all', 1.0)]\n"
    "for j, (depth, dirname, colname, alpha) in enumerate(specs):\n"
    "    for i, m in enumerate(['sasrec', 'marius']):\n"
    "        vals = [pd.read_csv(EXT / dirname / f'split_conformal_{c}.csv').query('model == @m')[colname].mean()\n"
    "                for c in CATS]\n"
    "        off = (j * 2 + i - 1.5) * 0.2\n"
    "        axes[0].bar(x + off, vals, 0.19, color=COL[m], alpha=alpha,\n"
    "                    label=f'{m.upper()}, depth {depth}')\n"
    "axes[0].set_xticks(x); axes[0].set_xticklabels([SHORT[c] for c in CATS])\n"
    "axes[0].set_ylabel('coverage ceiling (Recall@depth)')\n"
    "axes[0].set_title('depth-20 vs depth-100 ceilings'); axes[0].legend(ncol=2, loc='upper center')\n"
    "tidy(axes[0])\n"
    "\n"
    "mo = pd.read_csv(EXT / 'conformal' / 'mondrian_Beauty.csv')\n"
    "mo = mo[(mo.target_coverage == 0.08) & mo.achievable]\n"
    "buckets = ['hist<=5', 'hist6-15', 'hist>=16']\n"
    "xb = np.arange(3)\n"
    "for i, m in enumerate(['sasrec', 'marius']):\n"
    "    g = mo[mo.model == m].groupby('bucket')['k_star'].mean().reindex(buckets)\n"
    "    axes[1].bar(xb + (i - 0.5) * 0.36, g.values, 0.34, color=COL[m], label=m.upper())\n"
    "axes[1].set_xticks(xb); axes[1].set_xticklabels(['cold\\n(<=5)', 'medium\\n(6-15)', 'warm\\n(>=16)'])\n"
    "axes[1].set_ylabel('set size for 8% guarantee')\n"
    "axes[1].set_title('Beauty: set size by user history'); axes[1].legend(); tidy(axes[1])\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 7. Fusion ablation\n"
    "\n"
    "MARIUS combines an item's four code embeddings into one history token by "
    "summing them, a choice inherited from audio models that ignores which "
    "digit carried the information. We replaced the sum with level-aware "
    "alternatives (a per-level gain, and a small attention over the four "
    "digits), in a subclass that leaves the authors' code untouched and "
    "matches the baseline exactly at initialization, then retrained on Beauty "
    "(3 seeds).\n"
    "\n"
    "Accuracy is unchanged: the fusion is not the bottleneck, which "
    "concentrates the remaining evidence on the decoding stage. The per-level "
    "gain variant does shift every beyond-accuracy metric slightly in the "
    "favourable direction at no accuracy cost."
)

code(
    "fig, axes = plt.subplots(1, 2, figsize=(11, 3.6))\n"
    "arms = [('baseline\\n(sum)', EXT / 'baseline_scur1217' / 'marius_beauty_5seed_full_scores.jsonl', NEUTRAL),\n"
    "        ('level_gain', EXT / 'fuse' / 'level_gain' / 'marius_beauty_5seed_full_scores.jsonl', ACCENT),\n"
    "        ('attn', EXT / 'fuse' / 'attn' / 'marius_beauty_5seed_full_scores.jsonl', '#8172b3')]\n"
    "means = []\n"
    "for xi, (label, path, c) in enumerate(arms):\n"
    "    mean, std = jsonl_r10(path); means.append(mean)\n"
    "    axes[0].bar(xi, mean, 0.6, yerr=std, color=c, ecolor='#999', capsize=3, error_kw={'lw': 1})\n"
    "labels(axes[0], range(3), means, dy=0.06)\n"
    "axes[0].set_xticks(range(3)); axes[0].set_xticklabels([a[0] for a in arms])\n"
    "axes[0].set_ylabel('test Recall@10 (%), 3 seeds'); axes[0].set_ylim(7.6, 8.7)\n"
    "axes[0].set_title('fusion variant accuracy (Beauty)'); tidy(axes[0])\n"
    "\n"
    "base = pd.read_csv(EXT / 'beyond_accuracy_Beauty.csv')\n"
    "b = base[(base.model == 'marius') & (base.k == 10)].iloc[0]\n"
    "metrics = [('coverage_mean', 'coverage'), ('tail_recall_mean', 'tail recall'),\n"
    "           ('aplt_mean', 'long-tail share'), ('gini_mean', 'Gini'), ('arp_mean', 'avg popularity')]\n"
    "y = np.arange(len(metrics))\n"
    "for i, (arm, c) in enumerate([('level_gain', ACCENT), ('attn', '#8172b3')]):\n"
    "    df = pd.read_csv(EXT / 'fuse' / f'beyond_accuracy_Beauty_{arm}.csv')\n"
    "    row = df[df.k == 10].iloc[0]\n"
    "    rel = [100 * (row[mc] - b[mc]) / b[mc] for mc, _ in metrics]\n"
    "    axes[1].barh(y + (i - 0.5) * 0.36, rel, 0.34, color=c, label=arm)\n"
    "axes[1].axvline(0, color='#999', lw=0.8)\n"
    "axes[1].set_yticks(y); axes[1].set_yticklabels([lbl for _, lbl in metrics])\n"
    "axes[1].set_xlabel('% change vs baseline'); axes[1].invert_yaxis()\n"
    "axes[1].set_title('beyond-accuracy change (Gini, popularity: lower is better)')\n"
    "axes[1].legend(); tidy(axes[1], ygrid=False); axes[1].xaxis.grid(True, color='#e6e6e6', lw=0.8)\n"
    "plt.tight_layout(); plt.show()"
)

# =========================================================================== #
md(
    "## 8. Synthesis\n"
    "\n"
    "The results form a single line of argument about catalog collapse in "
    "semantic-ID generative recommenders.\n"
    "\n"
    "| Question | Evidence |\n"
    "|---|---|\n"
    "| Is there a failure mode? | The diversity profile inverts with dataset density; Sports coverage is 0.39 vs 0.74. |\n"
    "| Does it matter? | 22 to 23% of training demand is never recommended by the generative model. |\n"
    "| Why does it happen? | Weak code-pair families are pruned at the second digit; items lose to prefix siblings (r = -0.62). Robust across two codebooks. |\n"
    "| Where is the cause? | Not the fusion (ablation is null); the decoding stage (the depth-100 ceiling crossover). |\n"
    "| What helps already? | MBR gives a tunable accuracy-vs-reach trade-off; conformal sets give guarantees and a usable uncertainty signal. |\n"
    "| What is still open? | A decoder that targets the mechanism directly, adding exploration at the second digit, aiming to improve on the MBR trade-off. |\n"
    "\n"
    "A natural extension is the scale axis: with a fixed 256-way codebook, the "
    "number of items per prefix grows with the catalog, so the mechanism "
    "predicts the collapse should worsen on the large Amazon-2023 datasets "
    "even as accuracy improves. This remains untested.\n"
    "\n"
    "The reproduction is on `main`; all extension code, dumps, and results "
    "are on the `stanislaw` branch, with provenance documented in "
    "`CODE_OVERVIEW.md`."
)

nb["cells"] = cells
out = Path(__file__).resolve().parents[2] / "notebooks" / "project_story.ipynb"
nbf.write(nb, str(out))
print("wrote", out)
