defaults: 
- _self_
- paths
- disable_hydra_dirs

optim: 
  lr: 1e-3
  warmup: 100
  beta2: 0.99
  use_scheduler: true 
  weight_decay: 0 
  dropout_prob: 0.1
  batch_size: 256
  epochs: 500 # 192 steps/epochs on Arts -> 3125 epochs = 600k steps, adapt to category.
  eval_step: 100

centroids: 
  kmeans_init: true
  kmeans_iters: 100 
  sk_epsilons: [0., 0., 0., 0.003]
  sk_iters: 50
  n_centroids_list: [256, 256, 256, 256]

model: 
  layers: [1024, 512, 256, 128]

loss: 
  reconstruction_weight: 1.0
  contrastive_weight: 0.001
  tau: 2 
  bias: -8
  freeze_tau: false 
  freeze_bias: false
  sequence_length: 20

data:
  category: Video_Games
  emb_method: sentence-t5-xl

num_gpus: 1
ckpt_dir: /data/ebay-slc-a100/notebooks/udthakur/cosette_and_marius/output/cosette

marker: null