defaults:
- _self_
- experiment: ??? # Will override model, data, ...
- disable_hydra_dirs
- paths

# task name, determines output directory path
task_name: ??? # Overriden by experiment selection
date: ${now:%y%m%d}_${now:%H%M%S}

trainer: 
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: auto
  strategy:
    _target_: ray.train.lightning.RayDDPStrategy
  plugins:
    _target_: ray.train.lightning.RayLightningEnvironment
  precision: bf16-mixed
  check_val_every_n_epoch: null
  val_check_interval: 10_000
  limit_val_batches: 1000 # Reduce for faster (approximate) validation
  max_steps: 81_000 # Overriden by experiment selection
  # CALLBACKS
  callbacks: 
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: -1
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
    log_momentum: False
    log_weight_decay: True
  - _target_: src.utils.callbacks.CustomReportCallback
  # LOGGING 
  logger:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: null # Overriden with run name in code
    project: ${paths.wandb_project_name}
    entity: ${paths.wandb_entity}
    mode: ${paths.wandb_mode}

model: # Lightning Module for Training 
  _target_: src.lightning_module.LitModule
  net: null # Overriden by experiment selection
  mode: ??? # Overriden by experiment selection
  optimizer: 
    _target_: torch.optim.AdamW
    _partial_: true
    fused: true
    lr: ??? # Overriden by experiment selection
    weight_decay: ??? # Overriden by experiment selection
  scheduler: 
    _target_: src.utils.scheduler.CosineScheduler
    _partial_: true
    warmup_steps: ???
    cosine_steps: ${eval:'${trainer.max_steps} - ${model.scheduler.warmup_steps}'}

ray: 
  scaling_config:
    _target_: ray.train.ScalingConfig
    num_workers: 2
    use_gpu: True
    resources_per_worker:
      CPU: 4 # The rest is handled by Ray Data (24 CPUs: 2x4=8 training, 16 for pipeline)
      GPU: 1
  run_config:
    _target_: ray.train.RunConfig
    storage_path: ${paths.model_folder_tplt}
    checkpoint_config:
      _target_: ray.train.CheckpointConfig
      num_to_keep: 2
      checkpoint_score_attribute: valid/${data.ray_datasets.category}/HR@10
      checkpoint_score_order: max
    failure_config:
      _target_: ray.train.FailureConfig
      max_failures: 0
  runtime_env: {}


data: 
  ray_datasets: 
    _target_: src.data.ray_data.make_ray_dataset
    category: Video_Games
    total_len: ${eval:'${trainer.max_steps}*${data.datamodule.train_batch_size}'}
    emb_id: ??? # Overriden by experiment selection
    quant_id: ??? # Overriden by experiment selection
    num_cpus: 4 # Depends on the machine (24 CPUs: 2x4=8 training, 4 ToRow, 12 PrePro)
    prepro_cfg: 
      _cls_: ??? # Overriden by experiment selection
      crop_length: 50
      augment: timewise_shuffle
  datamodule:
    _target_: src.data.datamodule.RayDataModule
    train_batch_size: 256
    valid_batch_size: 256



    